/**
 * @fileoverview An entry point of the web app. This script was automatically
 * generated by googkit.
 */


goog.provide('googkit_index');/*@provide_main@*/

// goog.require('foo.Example');
goog.require('foo.ExampleToolbar');


// TODO: Write your code here
// var example = new foo.Example();
// example.doSomething();
// var exampleToolbar = new foo.ExampleToolbar();
// exampleToolbar.decorate();

function initialize() {
  var latlng = new google.maps.LatLng(35.709984,139.810703);
  var opts = {
    zoom: 15,
    center: latlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("map_canvas"), opts);
};
