// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/example-toolbar.js', ['foo.ExampleToolbar'], ['goog.dom', 'goog.events', 'goog.style', 'goog.ui.Component.EventType', 'goog.ui.Toolbar', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarToggleButton'], false);
goog.addDependency('../../../../development/js_dev/example.js', ['foo.Example'], ['goog.array', 'goog.crypt.base64', 'goog.dom', 'goog.dom.classes', 'goog.events', 'goog.net.EventType', 'goog.net.XhrIo', 'net.Ajax'], false);
goog.addDependency('../../../../development/js_dev/googkit_index.js', ['googkit_index'], ['foo.Example', 'foo.ExampleToolbar'], false);
goog.addDependency('../../../../development/js_dev/net/ajax.js', ['net.Ajax'], ['goog.net.XhrIo'], false);
