// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/example-toolbar.js', ['foo.ExampleToolbar'], ['goog.dom', 'goog.events', 'goog.style', 'goog.ui.Component.EventType', 'goog.ui.Toolbar', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarToggleButton'], false);
goog.addDependency('../../../../development/js_dev/example.js', ['foo.Example'], ['goog.array', 'goog.crypt.base64', 'goog.dom', 'goog.dom.classes', 'goog.events', 'goog.net.EventType', 'goog.net.XhrIo', 'net.Ajax'], false);
goog.addDependency('../../../../development/js_dev/googkit_index.js', ['googkit_index'], ['foo.Example', 'foo.ExampleToolbar'], false);
goog.addDependency('../../../../development/js_dev/map/map-manager.js', ['map.MapManager'], ['goog.array', 'util.MarkerUtil', 'util.UrlUtil'], false);
goog.addDependency('../../../../development/js_dev/net/ajax.js', ['net.Ajax'], ['goog.events', 'goog.net.EventType', 'goog.net.XhrIo'], false);
goog.addDependency('../../../../development/js_dev/toilet-map-app.js', ['toilet-map-app'], ['goog.dom', 'goog.events', 'goog.events.EventType', 'goog.ui.Popup', 'map.MapManager', 'net.Ajax', 'util.UrlUtil'], false);
goog.addDependency('../../../../development/js_dev/util/marker-util.js', ['util.MarkerUtil'], [], false);
goog.addDependency('../../../../development/js_dev/util/url-util.js', ['util.UrlUtil'], [], false);
